version: '3.8'

services:
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  api:
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - uploads:/uploads
    environment:
      - DATABASE_URL=mongodb://mongo_db:27017/barcamp8
      - ORIGIN_URL=http://ec2-54-169-232-140.ap-southeast-1.compute.amazonaws.com
      - GOOGLE_CLIENT_ID=1088133578350-0r8gk08t0j2vi15290d8eiv87kt16qn0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - PORT=8080
    depends_on:
      - mongo_db
    restart: always

volumes:
  uploads:
